name: Format

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '26'
      - name: Install deps
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted

