name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: throw
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '26'
      - name: Map postgres-db to localhost
        run: echo "127.0.0.1 postgres-db" | sudo tee -a /etc/hosts
      - name: Install deps
        run: mix deps.get
      - name: Setup test DB
        run: MIX_ENV=test mix ecto.create && MIX_ENV=test mix ecto.migrate
      - name: Run tests
        run: MIX_ENV=test mix test

